apivideo/api.video-api-client-generator

templates/java/statics/android-uploader/CHANGELOG.md
templates/java/statics/android/CHANGELOG.md

Update android client and android uploader changelogs.

chore(android): update android targets changelog

---

config/android-uploader.yaml
config/android.yaml
templates/java/libraries/okhttp-gson/build.gradle.mustache
templates/java/maven-push.gradle.mustache
templates/java/post-generate-android-uploader.sh
templates/java/post-generate-android.sh
templates/java/statics/android-uploader/.github/workflows/release.yml
templates/java/statics/android/.github/workflows/release.yml

Fix gradle publishing plugin configuration for Android targets (client and uploader)

fix(android): fix gradle publishing plugin configuration

---

templates/swift5/README.mustache

fix(swift5): Fix readme links

---

templates/swift5/api.mustache

Fix iOS video uploader compilation

Revert "feat(*): add a new swift5/ios client"

---

templates/swift5/README.mustache

fix(swift5): fix cocoapods installation

---

templates/swift5/README.mustache

fix(swift5): fix swift code block

---

config/android-uploader.yaml
config/android.yaml
config/java.yaml
templates/java/IProgressiveUploadSession.mustache
templates/java/libraries/okhttp-gson/api.mustache

feat(java): Use an interface for progressive upload session

feat(java): Use an interface for progressive upload session

---

config/swift5-uploader.yaml
config/swift5.yaml
templates/swift5/Upload/ProgressiveUploadSessioning.mustache
templates/swift5/api.mustache

feat(swift5): Use a protocol for progressive upload session

feat(swift5): Use a protocol for progressive upload session

---

config/swift5.yaml
templates/swift5/Upload/ProgressiveUploadSessioning.mustache

fix(swift5): Fix progressive upload protocol visibility

fix(swift5): Fix progressive upload protocol visibility

---

config/swift5-uploader.yaml

chore(swift5): bump upload to 0.1.2

chore(swift5): bump upload to 0.1.2

---

config/android-uploader.yaml
config/android.yaml
templates/java/libraries/okhttp-gson/build.gradle.mustache
templates/java/statics/android-uploader/example/build.gradle
templates/java/statics/android/example/build.gradle

bugfix(android): Fix Android min Sdk version

bugfix(android): Fix Android min Sdk version

---

templates/java/libraries/okhttp-gson/build.gradle.mustache
templates/java/statics/android-uploader/.github/workflows/create-release-from-changelog.yml
templates/java/statics/android-uploader/.github/workflows/release.yml
templates/java/statics/android-uploader/.github/workflows/test.yml
templates/java/statics/android-uploader/.github/workflows/update-documentation.yml
templates/java/statics/android/.github/workflows/create-release-from-changelog.yml
templates/java/statics/android/.github/workflows/release.yml
templates/java/statics/android/.github/workflows/test.yml
templates/java/statics/android/.github/workflows/update-documentation.yml
templates/java/statics/android/src/androidTest/java/video/api/integration/VideosTest.java
templates/java/statics/android/src/androidTest/java/video/api/integration/WebhooksTest.java
templates/java/statics/android/src/androidTest/java/video/api/integration/utils/Utils.java

CI for instrumented tests for Android client

chore(android): add CI for instrumented tests on client

---

templates/java/libraries/okhttp-gson/build.gradle.mustache
templates/java/libraries/okhttp-gson/build.sbt.mustache
templates/java/libraries/okhttp-gson/pom.mustache

Fix security alert on gson version < 2.8.9

fix(java): upgrade gson to fix security alert

---

config/android.yaml
templates/java/libraries/okhttp-gson/README.mustache
templates/java/libraries/okhttp-gson/api.mustache
templates/java/libraries/okhttp-gson/build.gradle.mustache
templates/java/statics/android/src/androidTest/java/video/api/integration/VideosAsyncTest.java
templates/java/statics/java/src/test/java/video/api/integration/VideosAsyncTest.java

Add async API for Java and android

feat(android): add async API

---

config/android-uploader.yaml
config/android.yaml
templates/java/android/services/UploadService.mustache
templates/java/android/services/UploadServiceListener.mustache
templates/java/android/services/UploadTask.mustache
templates/java/statics/android-uploader/example/src/main/java/video/api/uploader/example/MainActivity.kt
templates/java/statics/android/example/src/main/java/video/api/client/example/MainActivity.kt

Android service:
- Add upload id in onComplete()
- Add API to create progressive upload sessions for video id or upload token
- Add API so the service can be bind again

fix(java): android service: add API and improve service usage

---

templates/java/android/services/UploadService.mustache
templates/java/statics/android-uploader/example/src/main/java/video/api/uploader/example/CustomUploaderService.kt
templates/java/statics/android/example/src/main/java/video/api/client/example/CustomUploaderService.kt
templates/java/statics/android/src/androidTest/java/video/api/integration/UploadServiceTest.java
templates/java/statics/android/src/androidTest/java/video/api/integration/services/UploadServiceWithoutNotifications.java

fix(java): fix Android service test

---

templates/swift5/Upload/FileChunkInputStream.mustache
templates/swift5/Upload/RequestTaskQueue.mustache
templates/swift5/Upload/UploadChunkRequestTaskQueue.mustache

fix(ios): replace ApiVideoClient by project name

---

config/swift5-uploader.yaml
config/swift5.yaml
templates/swift5/Upload/ProgressiveUploadSessionProtocol.mustache
templates/swift5/Upload/RequestTaskQueue.mustache
templates/swift5/Upload/UploadChunkRequestTaskQueue.mustache
templates/swift5/api.mustache
templates/swift5/statics/client/.github/workflows/build.yml
templates/swift5/statics/client/Tests/ApiVideoClient/Integration/VideosApiTests.swift
templates/swift5/statics/uploader/.github/workflows/build.yml

fix(ios): fix the way RequestTaskQueue operation is synchronous

---

README.md
templates/csharp/README.mustache
templates/go/README.mustache
templates/java/libraries/okhttp-gson/README.mustache
templates/nodejs/README.md.mustache
templates/php/README.mustache
templates/python/README.mustache
templates/swift5/README.mustache

chore(*): migrate banner to .github

---

oas_apivideo.yaml

Same as https://github.com/apivideo/api.video-api-specification/pull/53

Update parameter descriptions and add enums

---

templates/documentation/sdks/nocode/wordpress.md

Added frontmatter to `wordpress.md`: title, slug, metadata

Add SEO tags to wordpress.md

---

templates/documentation/sdks/nocode/strapi.md

Strapi page addition to the docs

No-code/Strapi

---

templates/documentation/README.md

Removing incorrect partial code that resulted in this error:

Remove incorrect partial code

---

templates/documentation/get-started/start-building.md

Added delivery quickstart to start building

---

templates/documentation/doctave.yaml
templates/documentation/reference/invalid-query-parameter.md
templates/documentation/reference/navigation.yaml

Sébastien found pages that were not redirected from ReadMe to Doctave. The list is [here](https://docs.google.com/spreadsheets/d/1UGy7wiaSHIHR2_tdxNaE8bERgvf3_Q39BrZmxPpWo9Q/edit#gid=1027795030).
**Summary**
- add missing redirects to `doctave.yaml`
- add a missing page ([Invalid Query Parameter error](https://docs.api.video/reference/invalid-query-parameter))

Add missing page and redirects

---

templates/documentation/doctave.yaml

Added a missing `/vod/` to one of the redirects.

Quick redirect fix

---

templates/documentation/vod/progressive-upload.md
templates/documentation/vod/upload-a-video-regular-upload.md
templates/documentation/vod/video-best-practices.md

Changes are for [this Asana task](https://app.asana.com/0/1205448597201625/1205518748289555).
**Summary**:
I updated the blog links from specific articles to article categories on these pages:
- https://docs.api.video/vod/video-best-practices
- https://docs.api.video/vod/upload-a-video-regular-upload
- https://docs.api.video/vod/progressive-upload

Update video upload blog links

---

templates/documentation/get-started/start-building.md

Quick fix for an image file path.

Fix get started flowchart image path

---

templates/documentation/vod/delegated-upload-tokens.md

Fix Upload token flowchart image path

---

oas_apivideo.yaml

Changes are for [this Asana task](https://app.asana.com/0/1204307844224163/1205692342927430).
**Summary**:
- add description to `clip` object in Create video object request schema
- add description and example to `startTimecode` and `endTimecode`

Update video-clip schema with descriptions

---

templates/documentation/vod/video-best-practices.md

Fixed the last mention of the earlier file size limit from 10GiB to 20GiB.

Fix 10GiB to 20GiB

---

apivideo-generator/src/main/java/video/api/client/generator/Php.java
config/php.yaml
templates/php/src/BaseClient.mustache
templates/php/src/Exception/AuthenticationFailedException.php

Thanks @groupecomplus for the fix.

fix(php): Added missing AuthenticationFailedException
