apivideo/api.video-api-client-generator

templates/swift5/README.mustache
Add cocoapods installation notice in README for iOS API client and iOS video uploader.
=> fix(swift5): Add cocoapods installation notice in README

templates/swift5/README.mustache
Add missing link to Carthage repo
=> fix(swift5): add missing link to Carthage repo

config/nodejs.yaml, oas_apivideo.yaml, templates/nodejs/test/sandbox.spec.ts.mustache
Fix player bug - the “Link active color” doesn’t save
=> fix(oas): add missing linkActive field in player upload/create payload

oas_apivideo.yaml
Fix an issue reported by @szekelyzol:
The oas `badrequest` field `problem` is the same type of `badrequest`.
=> Update bad-request schema

apivideo-generator/src/main/java/video/api/client/generator/Swift5.java
In example such as https://github.com/apivideo/api.video-ios-client/blob/main/docs/LiveStreamsAPI.md#example
The object class should be`LiveStreamCreationPayload` and not `live-stream-creation-payload`.
Example
```
let liveStreamCreationPayload = live-stream-creation-payload(name: "name_example", record: true, _public: false, playerId: "playerId_example") // LiveStreamCreationPayload | 
```
=> fix(swift5): fix model example in documentation

templates/documentation/vod/list-videos-2.md
This change is for [this Asana task](https://app.asana.com/0/1204577546714196/1205364682863051).
Summary: I updated the referenced file names (code-tab.html) and the content tags in the include functions. The affected page is `VOD/list-videos.md`.
This is also a test commit for the new repo :)
=> Fix code snippet tab includes

templates/documentation/get-started/create-and-manage-tokens-for-delegated-uploads.md, templates/documentation/get-started/upload-a-video-with-a-delegated-token.md, templates/documentation/live-streaming/working-with-live-streams.md, templates/documentation/vod/creating-and-managing-chapters.md, templates/documentation/vod/list-videos-2.md, templates/documentation/vod/upload-a-video-regular-upload.md
Changes are for [this Asana task](https://app.asana.com/0/1204577546714196/1205364682863051).
Summary: Multi-tab code snippets have been migrated incorrectly from ReadMe to Doctave, and they are rendered as separate code blocks.
Fix is based on this: https://www.notion.so/apivideo/Using-Doctave-b10f8678082747c890017960a0923347?pvs=4#7a048baffc1741e4a98c6002cb16f4f1
=> Bugfix: multitab code snippets

templates/documentation/doctave.yaml
Doctave released a new version that now supports [links and CTA buttons in the header](https://docs.doctave.com/docs/contents/header-links-cta). Adding them through this commit.
=> Feature add header buttons 2

templates/documentation/delivery-analytics/player-customization.md
Based on [this Asana task](https://app.asana.com/0/1204577546714196/1204576701641412).
Contents are from the original page [here](https://docs.api.video/reference/player-themes).
**To do**, in a different branch: move images from ReadMe to the repo.
=> Create player customization page

templates/documentation/vod/add-captions.md
Changes are for [this Asana task](https://app.asana.com/0/1204577546714196/1204675556698276).
I migrated the [Captions guide from ReadMe](https://docs.api.video/reference/captions) to Doctave.
=> Add captions guide

templates/documentation/vod/creating-and-managing-chapters.md
Changes are for [this Asana task](https://app.asana.com/0/1204577546714196/1205405872477618).
Some context about creating VTT files was missing from the Chapters guide.
=> Migrate VTT section to Chapters guide

templates/documentation/vod/creating-and-managing-chapters.md
Fixed incorrect VTT formatting on this page: https://api-video.doctave.dev/vod/creating-and-managing-chapters
Incorrect formatting was due to markdown artifacts from migration.
Before:
```
{
"codes": [
{
"code": "WEBVTT  </br>  </br>  01\n00:01.000 --> 00:04.000\n\n02\n00:05.000 --> 00:09.000",
"language": "text"
}
]
}
```
After:
```
WEBVTT
01
00:01.000 --> 00:04.000
02
00:05.000 --> 00:09.000
```
=> Fix VTT formatting on Chapters page

templates/documentation/vod/add-a-thumbnail-to-your-video.md, templates/documentation/vod/delete-a-video.md, templates/documentation/vod/list-videos-2.md, templates/documentation/vod/navigation.yaml, templates/documentation/vod/show-video-details.md, templates/documentation/vod/update-video-details.md, templates/documentation/vod/video-management-basics.md
Changes are for [this Asana task](https://app.asana.com/0/1204370684353095/1205405872477623).
Summary: 
- I moved these sections to parent page `templates\documentation\vod\video-management-basics.md`:
- Choose an api.video client
- Installation
- Retrieve your API key
- I removed above sections from all child pages under Video management basics:
- List Videos
- Show Video Details
- Update Video Details
- Add A Thumbnail To Your Video
- Delete A Video
=> Simplify video management basics pages

oas_apivideo.yaml
Quick fix to replace `x-readme` to `x-doctave` across the OAS, to enable displaying the code samples for every API operation.
=> Fix code sample fields to x-doctave

templates/documentation/reference/navigation.yaml
Changes are for [this Asana task](https://app.asana.com/0/1204307844224163/1205437532729412).
The [Authentication Errors](https://docs.api.video/reference/errors) section in the API reference had some issues due to migration, I fixed it according to the original page structure.
=> Fix error page structure

templates/documentation/delivery-analytics/navigation.yaml, templates/documentation/reference/navigation.yaml, templates/documentation/vod/demo-loom-clone.md, templates/documentation/vod/navigation.yaml
Changes are for [this Asana task](https://app.asana.com/0/1204370684353095/1205479956570331).
**Summary**:
- Move and rename [Analytics page](https://api-video.doctave.dev/delivery-analytics/analytics)
- Move and rename [Authentication page](https://api-video.doctave.dev/reference/authentication-guide)
- Rename [Bearer Token Authentication page](https://api-video.doctave.dev/reference/disposable-bearer-token-authentication)
- Fix Loom clone page title to [Loom mockup](https://api-video.doctave.dev/vod/demo-loom-clone)
- Hide currently empty pages from all navigation.yaml files:
```
- label: How to - analytics with api.video Player SDK
href: /delivery-analytics/how-to-player-sdk-analytics.md
- label: Video security best practices
href: /delivery-analytics/video-security-best-practices.md
- …
```
=> Update page nav structure

templates/documentation/README.md, templates/documentation/delivery-analytics/README.md, templates/documentation/doctave.yaml
Changes are for [this Asana task](https://app.asana.com/0/1204370684353095/1205483627562533).
**Summary**:
- Add content card for Delivery & analytics quickstart page on the [main landing page](https://api-video.doctave.dev/#quick-links), and the [Delivery & analytics landing page](https://api-video.doctave.dev/delivery-analytics#start-delivering-with-apivideo)
- Add "API status" link to header
=> Add cards for Delivery & analytics quickstart

templates/documentation/navigation.yaml
Changes are for [this Asana task](https://app.asana.com/0/1204577546714196/1205503121033208).
Summary: The Import tool link on [this page](https://api-video.doctave.dev/get-started/) should actually point to the import tool, and not a blog post about the import tool.
=> Update improt tool nav link

templates/documentation/doctave.yaml
Changes are for [this Asana task](https://app.asana.com/0/1204577546714196/1205503121033220).
Summary: renamed "API Status" to "Status page".
=> Rename API status header link

oas_apivideo.yaml
Changes are for [this Asana task](https://app.asana.com/0/1205448597201625/1205463553222545).
**Summary**:
I added the player logo file constraints to the description of the `/players/{playerId}/logo` request.
=> Add player logo file contraints to API reference

templates/documentation/_assets/css/components/quick-link.css
This PR is to fix an error introduced in [PR #275](https://github.com/apivideo/api.video-api-client-generator/pull/275).
**Summary**: 
`.quick-links-item.understand` CSS class was renamed to `.quick-links-item.resources` to fix the problem ✅
=> Fix quick link cards CSS

templates/documentation/vod/azure-cold-storage-backup.md, templates/documentation/vod/navigation.yaml
A new article about the Azure Cold storage & backup.
* Added a new article in VOD
* Added a new collapsable menu in VOD
=> Added a new article for Azure backup

oas_apivideo.yaml, templates/java/statics/android/src/test/java/video/api/client/api/clients/LiveStreamsApiTest.java, templates/java/statics/java/src/test/java/video/api/client/api/clients/LiveStreamsApiTest.java
As reported by @ThibaultBee: 
> in the API Reference of the Live Streams the thumbnail does not have a correct URL.
**Summary**:
I modified `cdn.api.video/live` to `live.api.video` in 2 instances.
=> Fix live stream thumbnail URL

templates/documentation/doctave.yaml
Changes are for [this Asana task](https://app.asana.com/0/1205448597201625/1205555708728069).
**Summary**: I added 3 redirects from the old Analytics endpoints to the new Analytics page.
=> Add missing Analytics redirects

templates/documentation/delivery-analytics/analytics.md, templates/documentation/reference/invalid-query-parameter.md, templates/documentation/sdks/livestream/apivideo-flutter-livestream.md, templates/documentation/sdks/player/apivideo-android-player-analytics.md, templates/documentation/sdks/player/apivideo-android-player.md, templates/documentation/sdks/player/apivideo-flutter-player.md, templates/documentation/sdks/player/apivideo-hlsjs-analytics.md, templates/documentation/sdks/player/apivideo-player-analytics.md, templates/documentation/sdks/player/apivideo-player-sdk.md, templates/documentation/sdks/player/apivideo-react-native-player.md, templates/documentation/sdks/player/apivideo-react-player.md, templates/documentation/sdks/player/apivideo-swift-player-analytics.md, templates/documentation/sdks/player/apivideo-swift-player.md, templates/documentation/sdks/player/apivideo-videojs-analytics.md, templates/documentation/sdks/vod/apivideo-android-uploader.md, templates/documentation/sdks/vod/apivideo-android-upstream.md, templates/documentation/sdks/vod/apivideo-flutter-uploader.md, templates/documentation/sdks/vod/apivideo-ios-uploader.md, templates/documentation/sdks/vod/apivideo-react-native-uploader.md, templates/documentation/sdks/vod/apivideo-typescript-media-recorder.md, templates/documentation/sdks/vod/apivideo-typescript-media-stream-composer.md, templates/documentation/sdks/vod/apivideo-typescript-uploader.md, templates/documentation/vod/delegated-upload-tokens.md, templates/documentation/vod/video-object.md
Changes are for [this Asana task](https://app.asana.com/0/1205448597201625/1205546610661012).
**Summary**:
- Updated each affected page to only have one H1 header and bumped header levels accordingly
- Fixed typos (for example instanciation -> instantiation)
- Fixed table formatting for some SKDs for better readability
- Removed duplicate table of contents sections (Doctave generates a table of contents for each page, no need to define one in the page body)
=> Fix duplicate H1 headers

templates/documentation/_partials/dark-light-image.md, templates/documentation/delivery-analytics/private-video-get-started.md, templates/documentation/delivery-analytics/private-video-session-tokens.md, templates/documentation/delivery-analytics/using-custom-domains.md, templates/documentation/delivery-analytics/video-privacy-access-management.md, templates/documentation/get-started/start-building.md, templates/documentation/live-streaming/restreams.md, templates/documentation/reference/authentication-guide.md, templates/documentation/reference/create-and-manage-webhooks.md, templates/documentation/reference/disposable-bearer-token-authentication.md, templates/documentation/vod/add-a-permanent-watermark.md, templates/documentation/vod/backup-and-cold-storage.md, templates/documentation/vod/delegated-upload-tokens.md, templates/documentation/vod/video-best-practices.md, templates/documentation/vod/video-object.md
Changes are for [this Asana task](https://app.asana.com/0/1205448597201625/1205705919925061).
**Summary**:
- Update `templates\documentation\_partials\dark-light-image.md` by adding `{{ alt }}` to the image alt brackets
- Update all images marked with orange [in this table](https://docs.google.com/spreadsheets/d/1JZv7zxKbgHNbu1-klqMqyni5pKf7mcJjKNosj0lucOM/edit#gid=545335800) on the **Missing alt attributes** tab with image alt descriptions.
=> Add alt texts to images in partials

config/android-uploader.yaml, config/android.yaml, config/swift5-uploader.yaml, config/swift5.yaml, oas_apivideo.yaml
The purpose of this PR is to rename `ios` project to `swift` project for consistency.
`ios-client` -> `swift-client`
`ios-uploader` -> `swift-uploader`
=> chore(*): rename ios to swift

templates/documentation/get-started/gcs-migration.md
**Summary**: the GCS migration guide had an incorrect image reference.
=> Fix GCS migration page image

templates/documentation/reference/README.md, templates/nodejs/post-generate.sh
Quick fix of 10 GiB to 20 GiB in the [API reference](https://docs.api.video/reference#limitation), with some formatting ease.
=> Fix video limitation in API reference

templates/documentation/sdks/api-clients/README.md
Follow-up change for [this Asana task](https://app.asana.com/0/1204370684353095/1205726620215780).
**Summary**:
On the API clients page, I referenced an icon in a partial like this:
```
{% include "_partials/hagrid-item.md" title: "PHP", image: "/_assets/icons/sdk_icons/php.svg", subtitle: "API client",  link: "././apivideo-php-client.md" %}
```
The important part is that the filname is lowercase: `php.svg` while in reality, the filename starts with a capital P: `Php.svg`. The Doctave desktop client renders the icon as expected, but when I published the site, I realized that the icon is not showing up. ⚠️ I've sent the issue to Doctave [on Slack](https://api-video.slack.com/archives/C05DTNR3QDS/p1698087648683989).
Fixing the filename in the path ✅
=> Fix php icon path on API clients page

templates/documentation/vod/video-object.md
Changes are for [this Asana task](https://app.asana.com/0/1205634133195403/1205769099134132).
**Summary**: I added these to the Video Object page:
* what is a video ID
* how it can be retrieved (via API, via dashboard)
=> Add VideoID explanation to Video object guide

templates/documentation/vod/video-download.md
Changes are for [this Asana task](https://app.asana.com/0/1205634133195403/1205913052808659).
**Summary**:
- the order of the code snippets was different between the 2 steps in the [Disable download for a video object](https://docs.api.video/vod/video-download#disable-download-for-a-video-object) section
- incorrect comment formatting in the Javascript example in the [Disable download for an existing video object](https://docs.api.video/vod/video-download#disable-download-for-an-existing-video-object) section
- Go example snippet was nested inside the Javascript example snippet in the [Disable download for an existing video object](https://docs.api.video/vod/video-download#disable-download-for-an-existing-video-object) section
=> Fix code snippets

templates/documentation/live-streaming/README.md, templates/documentation/vod/README.md
I've cleaned up the style formatting for the titles and intro paragraphs of the [VOD](https://docs.api.video/vod) and [Live streaming](https://docs.api.video/live-streaming) landing pages. 
This should eliminate the unnecessary space in the heading texts:
Also fixed a small typo: in the market --> on the market
=> Fix typos and style formatting

oas_apivideo.yaml
Changes are for [this Asana task](https://app.asana.com/0/1204307844224163/1206003116770297).
**Summary**: 
* Updated the description for the `language` parameter across all captions endpoints' request schemas
* Updated the code snippets where the `language` parameter is explained
* Updated the response schemas for all captions endpoints to contain the new `languageName` field
* Added `400` response schemas and response examples to all captions endpoints
* Added `languageName` to all example responses across captions endpoints
* Added descriptions to the `caption` response object schema
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1206003116770301
=> Update Captions in the API reference

oas_apivideo.yaml
Changes are for [this Asana task](https://app.asana.com/0/1204370684353095/1206058448022589).
Summary:
- remove references of Symfony from the language `parameter` under captions
- add link to the list of supported language tags to the [Captions guide](https://docs.api.video/vod/add-captions)
=> Update language param description

oas_apivideo.yaml
Changes are for [this Asana task](https://app.asana.com/0/1205634133195403/1206211746134025).
Slack thread: https://api-video.slack.com/archives/C04H2LRGF29/p1703066315590759
**Summary**: 
The `sortBy` attribute for `GET /live-streams` needs some updates:
- add `createdAt`, `updatedAt`, and `name` as enums
- format description (code formatting, line breaks)
- remove `publishedAt` from description
=> Update get live streams sortby attribute

oas_apivideo.yaml
Follow-up for [this Asana task](https://app.asana.com/0/1205634133195403/1206211746134025).
Slack thread: https://api-video.slack.com/archives/C04H2LRGF29/p1703066315590759
**Summary**:
- removed `publishedAt` from `sortBy` parameter description, and updated wording for the Go and Java code snippets for `GET /live-streams`
=> Update sortby in code snippets

config/android.yaml, config/csharp.yaml, config/go.yaml, config/java.yaml, config/nodejs.yaml, config/php.yaml, config/python.yaml, config/swift5.yaml, oas_apivideo.yaml
Context: [Slack](https://api-video.slack.com/archives/C04H2LRGF29/p1708077902670559)
Changes:
* removed `missing` enum
* added `ingesting` and `ingested` enums
* updated descriptions and formatting
=> Update VideoStatusIngest enum descriptions

oas_apivideo.yaml
⚠️ **This PR should not be merged before API rate limiting is released** ⚠️ 
Changes are for [this Asana task](https://app.asana.com/0/1205634133195403/1207037975949562).
Docs drafts are [here](https://www.notion.so/apivideo/API-rate-limiting-2ef948077a3748298c34be56a254578e).
**Summary**
* added the `429 - Too many requests` error response schema and example to every endpoint except `/auth`
* added the following response headers to the `200` response of `GET /videos` as a test:
* X-RateLimit-Limit
* X-RateLimit-Remaining
* X-RateLimit-Retry-After
⚠️ **This PR should not be merged before API rate limiting is released** ⚠️
=> Add API rate limiting to the OAS

oas_apivideo.yaml
Added a missing description for the `PATCH /videos/{videoId}/captions/{language}` operation.
=> Add missing parameter description

oas_apivideo.yaml
Following up on an issue ([Slack thread](https://api-video.slack.com/archives/C02104834UB/p1728483397033599)) related to how the `language` field is used, I added `nullable: true` as a property to it on these endpoints:
- `PATCH /videos/{videoId}`
- `POST /videos`
=> Add nullable property

apivideo-generator/src/main/java/video/api/client/generator/Java.java, config/android.yaml, config/csharp.yaml, config/go.yaml, config/java.yaml, config/nodejs.yaml, config/php.yaml, config/python.yaml, config/swift5.yaml, oas_apivideo.yaml, templates/php/README.mustache
Changes are for these Asana tasks:
- [Remove summary title](https://app.asana.com/0/1205386992201973/1208697246097961)
- [Select summary attributes individually](https://app.asana.com/0/1205386992201973/1208647488270061)
**Summary** 🤖
- Remove mentions of the `title` attribute of summary sources
- Add new parameters that enable summary creation with individual attributes:
- `transcriptSummaryAttributes`
- `attributes`
- Update description of `409` error for `PATCH /summaries/{summaryId}/source`
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1208702543603268
=> Update Summary endpoints

oas_apivideo.yaml
There is a limitation for Doctave at the moment that blocks the display of enums for a request parameter:
> Looks like we’re only showing the schema defined in items if the schema is an object.
In our case, the schema is for an array. Until Doctave fixes this issue, I've added the enums to the description.
=> Add missing description

oas_apivideo.yaml, templates/java/statics/android/src/androidTest/java/video/api/integration/WebhooksTest.java, templates/java/statics/android/src/test/java/video/api/client/api/clients/WebhooksApiTest.java, templates/java/statics/java/src/test/java/video/api/client/api/clients/WebhooksApiTest.java, templates/java/statics/java/src/test/java/video/api/integration/WebhooksTest.java
Changes are for [this Asana task](https://app.asana.com/0/1205634133195403/1208756299627438).
**Summary**
- Added the new webhooks: `video.caption.generated` and `video.summary.generated`
- Updated the Create Webhook endpoint description, request schema, and response schema to list the webhook events as enums for the `events` field
- Added link to Transcript guide in the description for the `generationMode` attribute
=> Add new webhooks

oas_apivideo.yaml
The `video.summary.generated` webhook accidentally had `video.caption.generated` as an example value.
=> Fix example value for summary webhook
